name: Terraform Plan

on:
  push:
    branches: ["main"]

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform fmt check
        id: fmt
        run: terraform fmt -check

      - name: Terraform init
        run: terraform init -backend=false

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: tfsec Terraform Security Scan
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: false
      - name: Trivy IaC Security Scan
        uses: aquasecurity/trivy-action@v0.19.0
        with:
          scan-type: config
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH,MEDIUM

      - name: Terraform Plan
        run: terraform plan
